version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOTPASS}
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOTPASS}
      - ME_CONFIG_MONGODB_SERVER=${DB_HOST}
  app-spring:
    container_name: app-spring
    build: .
    restart: always
    environment:
      - MONGO_AUTHENTICATION_DATABASE=${MONGO_AUTHENTICATION_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_ROOTPASS=${MONGO_ROOTPASS}
      - MONGO_DATABSE=${MONGO_DATABSE}
      - MONGO_PORT=${MONGO_PORT}
      - DB_HOST=${DB_HOST}
      - MONGO_INDEX_CREATE=${MONGO_INDEX_CREATE}
    ports:
      - 8080:8080
    links:
      - mongodb
volumes:
  data: {}

networks:
  default:
    name: mongodb_network