pipeline:
  identifier: Build_Daveu1983_mongo_spring_example_1706283224911
  name: Build mongo-spring-example
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1706283204303
        repoName: Daveu1983/mongo-spring-example
  stages:
    - stage:
        name: bld 1
        identifier: bld_1
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: mvn install
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Docker
        type: CI
